<?php

namespace App\Services;

use App\Repositories\ModuleRepository;
use CodeIgniter\Database\Exceptions\DatabaseException;

class ModuleService
{
    protected ModuleRepository $repository;
    protected MenuGeneratorService $menuGenerator;

    public function __construct()
    {
        $this->repository = new ModuleRepository();
        $this->menuGenerator = new MenuGeneratorService();
    }

    public function getAll(): array
    {
        return $this->repository->getAll();
    }

    public function getActive(): array
    {
        return $this->repository->getActive();
    }

    public function getById(int $id): ?array
    {
        return $this->repository->find($id);
    }

    public function create(array $data): int
    {
        $slug = trim(
            strtolower(
                (string) ($data['slug'] ?? '')
            )
        );

        if ($slug === '') {
            throw new \RuntimeException(
                'Module slug is required.'
            );
        }

        if ($this->repository->exists($slug)) {
            throw new \RuntimeException(
                'Module slug already exists.'
            );
        }

        $db = db_connect();

        $db->transBegin();

        try {

            $moduleId = $this->repository->create([
                'name'        => trim($data['name']),
                'slug'        => $slug,
                'icon'        => $data['icon'] ?? null,
                'route'       => $data['route'] ?? null,
                'description' => $data['description'] ?? null,
                'sort_order'  => (int) ($data['sort_order'] ?? 1),
                'status'      => $data['status'] ?? 'active',
            ]);

            /**
             * Generate default menu.
             *
             * Permissions are generated by MenuGeneratorService.
             */
            $this->menuGenerator->generate(
                $moduleId,
                $data['name'],
                $data['route'] ?? $slug,
                $data['icon'] ?? null,
                (int) ($data['sort_order'] ?? 1)
            );

            if (!$db->transStatus()) {
                throw new \RuntimeException(
                    'Module creation transaction failed.'
                );
            }

            $db->transCommit();

            return $moduleId;
        } catch (\Throwable $e) {

            $db->transRollback();

            throw $e;
        }
    }

    public function update(int $id, array $data): bool
    {
        return $this->repository->update($id, $data);
    }

    public function delete(int $id): bool
    {
        return $this->repository->delete($id);
    }

    public function getPaginated(array $filters): array
    {
        return $this->repository->paginate($filters);
    }
}
